#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
$secure = __DIR__.'/config.secure.json';
$secure = json_decode(file_get_contents($secure),1);
if (!$secure) {
    print 'Secure config has wrong format';die();
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

include(__DIR__ . '/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php');
include(__DIR__ . '/vendor/yiisoft/yii2/helpers/ArrayHelper.php');
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/static_config.php'),
    require(__DIR__ . '/config.local.php')
);

// Initialize PHP environment variables
if(isset($config['php_ini'])){
    foreach($config['php_ini'] as $key => $value){
        ini_set($key, $value);
    }
    unset($config['php_ini']);
}


unset($config['components']['errorHandler']);
unset($config['components']['user']);
unset($config['components']['session']);
unset($config['components']['request']);
$config['controllerNamespace'] = 'backend\commands';
Yii::setAlias('@web', __DIR__.'/public');
Yii::setAlias('@configs', __DIR__);
Yii::setAlias('@backend', __DIR__ . '/src');
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
